services:
  db:
    container_name: crud-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: sanctum
      MYSQL_DATABASE: crud_sanctum
      MYSQL_USER: sanctum
      MYSQL_PASSWORD: sanctum
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
